"use client";

import { useEffect, useState } from "react";
import { motion, useMotionValue, useSpring, useTransform } from "framer-motion";

export default function Background3D() {
  const [mounted, setMounted] = useState(false);
  const mouseX = useMotionValue(0);
  const mouseY = useMotionValue(0);

  // Smooth out the mouse movement
  const smoothX = useSpring(mouseX, { damping: 50, stiffness: 400 });
  const smoothY = useSpring(mouseY, { damping: 50, stiffness: 400 });

  // Transforms for parallax (x, y movement based on mouse)
  // Base background moves very little
  const bgX = useTransform(smoothX, [-1000, 1000], [10, -10]);
  const bgY = useTransform(smoothY, [-1000, 1000], [10, -10]);

  // Foreground trees move more
  const fgX = useTransform(smoothX, [-1000, 1000], [30, -30]);
  const fgY = useTransform(smoothY, [-1000, 1000], [30, -30]);

  useEffect(() => {
    setMounted(true);
    
    const handleMouseMove = (e: MouseEvent) => {
      // Calculate mouse position relative to center of screen
      const centerX = window.innerWidth / 2;
      const centerY = window.innerHeight / 2;
      mouseX.set(e.clientX - centerX);
      mouseY.set(e.clientY - centerY);
    };

    window.addEventListener("mousemove", handleMouseMove);
    return () => window.removeEventListener("mousemove", handleMouseMove);
  }, [mouseX, mouseY]);

  if (!mounted) return null;

  return (
    <div className="fixed inset-0 overflow-hidden bg-black pointer-events-none" style={{ zIndex: -1 }}>
      
      {/* BASE LAYER - Landscape */}
      <motion.div 
        className="absolute inset-[-5%] w-[110%] h-[110%] bg-cover bg-center bg-no-repeat"
        style={{ 
          backgroundImage: "url('/bg_landscape.png')",
          x: bgX,
          y: bgY,
        }}
      />

      {/* PARTICLES */}
      {/* A simple particle system overlaid on the background */}
      <div className="absolute inset-0">
        {Array.from({ length: 30 }).map((_, i) => {
          const size = Math.random() * 4 + 2;
          const left = Math.random() * 100;
          const delay = Math.random() * 10;
          const duration = Math.random() * 10 + 10;
          
          return (
            <motion.div
              key={i}
              className="absolute bg-[#00F0FF] rounded-full blur-[1px]"
              style={{
                width: size,
                height: size,
                left: `${left}%`,
                bottom: "-10%",
                boxShadow: "0 0 10px #00F0FF, 0 0 20px #FF007A",
              }}
              animate={{
                y: ["0vh", "-120vh"],
                opacity: [0, 1, 0],
                x: Math.random() * 100 > 50 ? [0, 50, -50, 0] : [0, -50, 50, 0],
              }}
              transition={{
                duration,
                repeat: Infinity,
                delay,
                ease: "linear",
              }}
            />
          );
        })}
      </div>

      {/* FOREGROUND LAYER - Left Palm Tree */}
      {/* mixBlendMode 'screen' removes the black background generated by AI */}
      <motion.div 
        className="absolute top-0 left-[-15%] md:left-[-5%] w-[70%] md:w-[40%] h-[120%] bg-contain bg-left bg-no-repeat origin-bottom"
        style={{ 
          backgroundImage: "url('/palm_tree_left.png')",
          mixBlendMode: "screen",
          x: fgX,
          y: fgY,
        }}
        animate={{
          rotate: [-1.5, 1.5, -1.5],
        }}
        transition={{
          duration: 8,
          repeat: Infinity,
          ease: "easeInOut",
        }}
      />

      {/* FOREGROUND LAYER - Right Palm Tree */}
      <motion.div 
        className="absolute top-0 right-[-15%] md:right-[-5%] w-[70%] md:w-[40%] h-[120%] bg-contain bg-right bg-no-repeat origin-bottom"
        style={{ 
          backgroundImage: "url('/palm_tree_right.png')",
          mixBlendMode: "screen",
          x: fgX,
          y: fgY,
        }}
        animate={{
          rotate: [1.5, -1.5, 1.5],
        }}
        transition={{
          duration: 10,
          repeat: Infinity,
          ease: "easeInOut",
        }}
      />

      {/* Gradient Overlay to ensure UI text remains readable over bright background spots */}
      <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/30 to-black/50" />
      <div className="absolute inset-0 bg-[#032A1C]/40 mix-blend-overlay" />
    </div>
  );
}
